var slide1text = "Education is considered to be the main way that low-income families can improve their economic position over time. However, a new study from the Equality of Opportunity Project suggests that this path to wealth is harder than ever. Elite colleges and universities are disproportionately attended by students from the wealthiest of wealthy families. This map shows every institution of higher education in the country, symbolized by the median family income of the student body. Orange points represent schools with the wealthiest students while purple ones show those with the lowest income student bodies.";

var slide2text = "In the previous map we saw how wealthy schools are distributed across the U.S. Students from high-income families are disproportionately located in the Northeast, Mid-Atlantic and in cities on the West Coast. There are also dramatic differences at a much more local level. For example, here in Manhattan, the student body at Columbia University has a median family income of nearly $170,000. Just over a mile north, students The City University of New York come from families with a median income of under $36,000.";

var slide3text = "188 schools have more students from the top 1% of U.S. households (measured by income) than they do from the bottom 20%. These schools are mapped to the right. The symbol sizes indicate the ratio of students who fall in the latter group as compared to those in the former. The largest circles represent the schools with the highest proportions of rich to poor students.";

var slide4text = "So where is higher education most accessible to low-income families? This map shows the proportion of college students coming from the bottom 20% of U.S. household median income for every Metropolitan Statistical Area (MSA) in the U.S. The orange MSAs have higher rates of low-income students than the purple ones.";

var slide5text = "Low-income student access doesn’t tell the whole story. We need to evaluate the success of low-income students in improving their income. The map to the right shows that success rate by MSA, that is the proportion of low-income students (families in the bottom quintile of income) that reached the top quintile. In orange MSAs low-income students have higher rates of success than in purple ones.";
